Console.WriteLine("Enter points");
int x1 = Convert.ToInt32(Console.ReadLine());
int x2 = Convert.ToInt32(Console.ReadLine());
int y1 = Convert.ToInt32(Console.ReadLine());
int y2 = Convert.ToInt32(Console.ReadLine());
double l1 = Math.Pow((x2 - x1), 2);
double l2 = Math.Pow((y2 - y1), 2);
double length = l1 + l2;
double line_lenght = Math.Sqrt(length);
Console.WriteLine("Length of line is " + line_lenght);